workflows:
  default-workflow:
    name: Flutter build
    max_build_duration: 60
    environment:
      flutter: 3.35.4   # ✅ locks Flutter version
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.aab
